name: Disallow "On Hold" PRs
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [master]

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "On Hold" label
        uses: egmacke/action-check-label@0eb29f801fb482a95c9bd2dd22834ecc8f4e8af9 # v2
        with:
          label: On Hold
          state: absent
